package main;

/**
 * Doubly linked list node - DO NOT EDIT THIS FILE.
 * 
 * @author Chami Lamelas
 *
 */
public class Node {
	
	public Node next;
	public Node prev;
	public char data;
	
	public Node(char c) {
		this.next = null;
		this.prev = null;
		this.data = c;
	}
	
	public String toString() {
		return "" + this.data;
	}
}
